/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.pacientes;

import controlador.PacienteControlador;
import javax.swing.JOptionPane;
import modelo.PacienteModelo;

/**
 *
 * @author rb940
 */
public class Ingresar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
        txt_edad.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_edadKeyTyped(evt);
        }
    });
    }
    private void txt_edadKeyTyped(java.awt.event.KeyEvent evt) {                                  
    char c = evt.getKeyChar();
    
    // Verificar si el carácter ingresado no es un número (0-9)
    if (!Character.isDigit(c)) {
        // Mostrar un mensaje de advertencia si el usuario ingresa una letra
        JOptionPane.showMessageDialog(this, "Solo se pueden ingresar números en el campo de edad.", 
                                      "Advertencia", JOptionPane.WARNING_MESSAGE);
        
        // Si se desea, se puede eliminar el carácter no válido (comentado si no lo deseas)
        // evt.consume();
    }

}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_sexo = new javax.swing.JComboBox<>();
        bttn_guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombres y Apellidos");

        jLabel3.setText("Edad");

        jLabel4.setText("Sexo");

        cbx_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        bttn_guardar.setText("Guardar");
        bttn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(bttn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_edad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_Nombres, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttn_guardar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_guardarActionPerformed
    String cedula = txt_cedula.getText();
    String nombre = txt_Nombres.getText();
    String edadStr = txt_edad.getText();
    boolean sexo = cbx_sexo.getSelectedItem().toString().equals("Hombre");
    
    // Validar si la edad ingresada es un número
    int edad = 0;
    try {
        edad = Integer.parseInt(edadStr); // Intentamos convertir la edad a un número entero
    } catch (NumberFormatException e) {
        // Si ocurre un error, mostramos un mensaje de error
        JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Detener la acción
    }

    // Verificar si ya existe un paciente con la misma cédula
    PacienteControlador pacienteControlador = PacienteControlador.getInstancia();
    
    if (pacienteControlador.existePacientePorCedula(cedula)) {
        // Si la cédula ya está registrada, mostramos un mensaje de error
        JOptionPane.showMessageDialog(this, "El número de cédula ya está registrado.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Si no existe, guardamos los datos del paciente
        PacienteModelo pm = pacienteControlador.guardarDatos(cedula, nombre, edad, sexo);
        JOptionPane.showMessageDialog(this, pm.getNombres() + " INGRESADO EXITOSAMENTE");

        // Limpiar las casillas de texto después de guardar los datos
        txt_cedula.setText("");
        txt_Nombres.setText("");
        txt_edad.setText("");
        cbx_sexo.setSelectedIndex(0); // Restablecer el combo box a "Hombre"
    }
    
    }//GEN-LAST:event_bttn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_guardar;
    private javax.swing.JComboBox<String> cbx_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_edad;
    // End of variables declaration//GEN-END:variables
}
